# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_pb2 as data__pb2


class StreamDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.data = channel.unary_unary(
                '/StreamDataService/data',
                request_serializer=data__pb2.Data.SerializeToString,
                response_deserializer=data__pb2.Mesh.FromString,
                )


class StreamDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def data(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'data': grpc.unary_unary_rpc_method_handler(
                    servicer.data,
                    request_deserializer=data__pb2.Data.FromString,
                    response_serializer=data__pb2.Mesh.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StreamDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StreamDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def data(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StreamDataService/data',
            data__pb2.Data.SerializeToString,
            data__pb2.Mesh.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
